config/routes.rb
Ammortamenti::Application.routes.draw do
  get "dashboard" => "dashboard#index", :as => "dashboard"

  get "dashboard/admin"

  resources :items

  
  resources :users
  resources :accounts do
	resources :payments
	member do
		post 'register'
		post 'unregister'
    end
  end

  resources :buildings do
	resources :offices
  end

  resources :categories

  resources :providers

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "sessions#new"
  resources :tests
  
  resources :sessions
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  
       user ||= User.new # guest user (not logged in)

    can :manage, :all

    #if (user.assignments.role == :admin &&
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table =>"users_accounts"
  has_many :payments
end

app/models/activity.rb
class Activity < ActiveRecord::Base
#this might be a comment or a post or something else
  belongs_to :changed_item, :polymorphic => true
  #who did it?
  belongs_to :user
  #what did he do?
  

  
  def msg
    #do fancy text generation
    if cambiamenti.new_record
      "#{user.name} created a #{changed_item.class}"
    else
      "#{user.name} changed #{cambiamenti.length} attributes of the #{changed_item.class} #{changed_item.title}"
    end
  end



end

app/models/building.rb
class Building < ActiveRecord::Base
	has_many :offices
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :offices, :through =>:items
	acts_as_taggable
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :payment
  belongs_to :category
  belongs_to :provider
  belongs_to :office
end

app/models/office.rb
class Office < ActiveRecord::Base
  belongs_to :building
  has_many :items
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :account
  has_many :providers, :through =>:items
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :items
end

app/models/test.rb
class Test < ActiveRecord::Base
	has_paper_trail
end

app/models/user.rb
class User < ActiveRecord::Base  
	has_secure_password
	validates_presence_of :username, :on => :create
	validates_presence_of :password, :on => :create
	validates :username, :uniqueness => true
	has_many :activities
	has_and_belongs_to_many :accounts, :join_table => "users_accounts"
	
	def prj_role?(base_role)
	  ""
  end
	
	def admin?
	
		if self.assignments.where("role = ?",'manager').length > 0 then
	
			true
		else
			false
		end
	end
	
end

app/models/user_session.rb
class UserSession
  def initialize(session)
    @session = session
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :require_user
  
  def index
	@accounts = current_user.accounts
	
  end

  def admin
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/dashboard/admin.html.erb
<h1><%= current_user.username %>'s dashboard</h1>

<div class="input">
	<li><%= link_to "All accounts", accounts_path, :class => "button big primary" %></li>
</div>

<br />
<br />

<h2>Registered accounts</h2>

<table>
  <tr>
    <th>Description</th>
    <th>Account</th>
    <th>User</th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.desc %></td>
    <td><%= account.account %></td>

    <td><%= User.find(account.user_id).username %></td>
    <td>
	<div class="button-group">
		<%= link_to 'Show', account_path(account), :class => "button primary icon search" %>
		<%= link_to 'Edit', edit_account_path(account), :class => "button icon edit"%>
		<%= link_to 'Un-Register', unregister_account_path(account), method: :post, :class => "button icon remove" %>
		<%= link_to 'Destroy', account_path(account), confirm: 'Are you sure?', method: :delete, :class => "button danger icon trash" %>
	</div>
	</td>
  </tr>
<% end %>
</table>

<br />

app/views/dashboard/index.html.erb
<h1><%= current_user.username %>'s dashboard</h1>

<div class="input">
	<li><%= link_to "All accounts", accounts_path, :class => "button big primary" %></li>
</div>

<br />
<br />

<h2>Registered accounts</h2>

<table class="boot">
  <tr>
    <th>Description</th>
    <th>Account</th>
    <th>User</th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.desc %></td>
    <td><%= account.account %></td>

    <td><%= User.find(account.user_id).username %></td>
    <td>
	<div style='text-align:right;'>
	<div class="button-group"  style="text-align:right;">
		<%= link_to 'Show', account_path(account), :class => "button primary icon search" %>
		<%= link_to 'Edit', edit_account_path(account), :class => "button icon edit"%>
		<%= link_to 'Un-Register', unregister_account_path(account), method: :post, :class => "button icon remove" %>
		<%= link_to 'Destroy', account_path(account), confirm: 'Are you sure?', method: :delete, :class => "button danger icon trash" %>
	</div>
	</div>
	</td>
  </tr>
<% end %>
</table>

<br />