config/routes.rb
Ammortamenti::Application.routes.draw do
  get "dashboard" => "dashboard#index", :as => "dashboard"

  get "dashboard/admin"

  resources :items

  
  resources :users
  resources :accounts do
	resources :payments
	member do
		post 'register'
		post 'unregister'
    end
  end

  resources :buildings do
	resources :offices
  end

  resources :categories

  resources :providers

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "sessions#new"
  resources :tests
  
  resources :sessions
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  
       user ||= User.new # guest user (not logged in)

    can :manage, :all

    #if (user.assignments.role == :admin &&
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table =>"users_accounts"
  has_many :payments
end

app/models/activity.rb
class Activity < ActiveRecord::Base
#this might be a comment or a post or something else
  belongs_to :changed_item, :polymorphic => true
  #who did it?
  belongs_to :user
  #what did he do?
  

  
  def msg
    #do fancy text generation
    if cambiamenti.new_record
      "#{user.name} created a #{changed_item.class}"
    else
      "#{user.name} changed #{cambiamenti.length} attributes of the #{changed_item.class} #{changed_item.title}"
    end
  end



end

app/models/building.rb
class Building < ActiveRecord::Base
	has_many :offices
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :offices, :through =>:items
	acts_as_taggable
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :payment
  belongs_to :category
  belongs_to :provider
  belongs_to :office
end

app/models/office.rb
class Office < ActiveRecord::Base
  belongs_to :building
  has_many :items
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :account
  has_many :providers, :through =>:items
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :items
end

app/models/test.rb
class Test < ActiveRecord::Base
	has_paper_trail
end

app/models/user.rb
class User < ActiveRecord::Base  
	has_secure_password
	validates_presence_of :username, :on => :create
	validates_presence_of :password, :on => :create
	validates :username, :uniqueness => true
	has_many :activities
	has_and_belongs_to_many :accounts, :join_table => "users_accounts"
	
	def prj_role?(base_role)
	  ""
  end
	
	def admin?
	
		if self.assignments.where("role = ?",'manager').length > 0 then
	
			true
		else
			false
		end
	end
	
end

app/models/user_session.rb
class UserSession
  def initialize(session)
    @session = session
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/new
  # GET /offices/new.json
  def new
    @office = Office.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.json
  def create
	@building = Building.find(params[:building_id])
    @office = @building.offices.create(params[:office])

    respond_to do |format|
      if @office.save
        format.html { redirect_to building_path(@building), notice: 'Office was successfully created.' }
        format.json { render json: @office, status: :created, location: @office }
      else
        format.html { render action: "new" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.json
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        format.html { redirect_to building_path(@office.building), notice: 'Office was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office = Office.find(params[:id])
	@building = @office.building
    @office.destroy

    respond_to do |format|
      format.html { redirect_to building_path(@building) }
      format.json { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/offices/_form.html.erb
<%= form_for([@office.building,@office]) do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :desc %>
	<div class="input">
		<%= f.text_field :desc %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :number %>
	<div class="input">
		<%= f.text_field :number %>
	</div>
  </div>

  <div class="input">
    <%= f.submit :class => "button primary" %>
	
<% end %>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render 'form' %>

<div class="button-group">
<%= link_to 'Show', building_office_path(@office.building,@office), :class => "button primary" %>
<%= link_to 'Back', @office.building, :class => "button danger" %>
</div>
</div>

app/views/offices/index.html.erb
<h1>Listing offices</h1>

<table class="boot">
  <tr>
    <th>Description</th>
    <th>Number</th>
    <th>Building</th>
    <th></th>
  </tr>

<% @offices.each do |office| %>
  <tr>
    <td><%= office.desc %></td>
    <td><%= office.number %></td>
    <td><%= office.building != nil ? office.building.desc: "" %></td>
    <td>
	<div style='text-align:right;'>
	<div class="button-group">
		<%= link_to 'Show', building_office_path(office.building, office), :class => "button primary" %>
		<%= link_to 'Edit', edit_building_office_path(office.building, office),:class => "button icon edit" %>
		<%= link_to 'Destroy', building_office_path(office.building, office), confirm: 'Are you sure?', method: :delete,:class => "button danger icon trash" %>
	</div>
	</div>
	</td>
  </tr>
<% end %>
</table>

<br />
<div class="input">
	<%= link_to 'New Office', new_building_office_path,:class => "button primary icon add" %>
</div>

app/views/offices/new.html.erb
<h1>New office</h1>

<%= render 'form' %>

<%= link_to 'Back', offices_path, :class => "button danger" %>
</div>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @office.desc %>
</p>

<p>
  <b>Number:</b>
  <%= @office.number %>
</p>

<p>
  <b>Building:</b>
  <%= @office.building != nil ? @office.building.desc: "" %>
</p>

<div class="button-group">
	<%= link_to 'Edit', edit_building_office_path(@office.building,@office), :class => "button primary" %>
	<%= link_to 'Back', building_path(@office.building), :class => "button danger" %>
</div>