config/routes.rb
Ammortamenti::Application.routes.draw do
  get "dashboard" => "dashboard#index", :as => "dashboard"

  get "dashboard/admin"

  resources :items

  
  resources :users
  resources :accounts do
	resources :payments
	member do
		post 'register'
		post 'unregister'
    end
  end

  resources :buildings do
	resources :offices
  end

  resources :categories

  resources :providers

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  root :to => "sessions#new"
  resources :tests
  
  resources :sessions
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  
       user ||= User.new # guest user (not logged in)

    can :manage, :all

    #if (user.assignments.role == :admin &&
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table =>"users_accounts"
  has_many :payments
end

app/models/activity.rb
class Activity < ActiveRecord::Base
#this might be a comment or a post or something else
  belongs_to :changed_item, :polymorphic => true
  #who did it?
  belongs_to :user
  #what did he do?
  

  
  def msg
    #do fancy text generation
    if cambiamenti.new_record
      "#{user.name} created a #{changed_item.class}"
    else
      "#{user.name} changed #{cambiamenti.length} attributes of the #{changed_item.class} #{changed_item.title}"
    end
  end



end

app/models/building.rb
class Building < ActiveRecord::Base
	has_many :offices
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :offices, :through =>:items
	acts_as_taggable
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :payment
  belongs_to :category
  belongs_to :provider
  belongs_to :office
end

app/models/office.rb
class Office < ActiveRecord::Base
  belongs_to :building
  has_many :items
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :account
  has_many :providers, :through =>:items
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :items
end

app/models/test.rb
class Test < ActiveRecord::Base
	has_paper_trail
end

app/models/user.rb
class User < ActiveRecord::Base  
	has_secure_password
	validates_presence_of :username, :on => :create
	validates_presence_of :password, :on => :create
	validates :username, :uniqueness => true
	has_many :activities
	has_and_belongs_to_many :accounts, :join_table => "users_accounts"
	
	def prj_role?(base_role)
	  ""
  end
	
	def admin?
	
		if self.assignments.where("role = ?",'manager').length > 0 then
	
			true
		else
			false
		end
	end
	
end

app/models/user_session.rb
class UserSession
  def initialize(session)
    @session = session
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource
  before_filter :require_user
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
	@accounts = @accounts - current_user.accounts
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])
	@payments = @account.payments
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
	@user = current_user
    @account = @user.accounts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
	params[:account][:user_id]=current_user.id
	@account = Account.new(params[:account])
	
	
	
    respond_to do |format|
      if @account.save
		current_user.accounts << @account
        format.html { redirect_to accounts_path, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to ApplicationCon, notice: 'Account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_path }
      format.json { head :ok }
    end
  end
  
  # POST /accounts/id/resgister
  # register an account for the watch list
  
  def register
	@account = Account.find(params[:id])
	
	@account.users << current_user
	
	 respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.json { head :ok }
    end
	
  end
  
  # POST /accounts/id/unresgister
  # un_register an account for the watch list
  
  def unregister
	@account = Account.find(params[:id])
	
	current_user.accounts.delete(@account) if current_user.accounts
	
	 respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.json { head :ok }
    end
	
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/accounts/_form.html.erb
<%= form_for([@account]) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :desc %>
	<div class="input">
		<%= f.text_field :desc %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :account %>
	<div class="input">
		<%= f.text_field :account %>
	</div>
  </div>

  <div class="input">
    <%= f.submit :class => "button primary" %>

<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>
<div class="button-group">
<%= link_to 'Show', @account, :class => "button" %>
<%= link_to 'Back', dashboard_path, :class => "button danger" %>
</div>
</div>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table class="boot">
  <tr>
    <th>Description</th>
    <th>Account</th>
    <th>User</th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.desc %></td>
    <td><%= account.account %></td>

    <td><%= User.find(account.user_id).username %></td>
    <td>
	<div style='text-align:right;'>
	<div class="button-group">
		<%= link_to 'Show', account_path(account), :class => "button primary icon search" %>
		<%= link_to 'Register', register_account_path(account), method: :post, :class => "button icon rss" %>
	</div>
	</div>
	</td>
  </tr>
<% end %>
</table>

<br />
<div class="input">
	<%= link_to 'New Account', new_account_path, :class => "button primary icon add" %>
	<%= link_to 'Back', dashboard_path, :class => "button danger icon home" %>
</div>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path, :class => "button danger" %>
</div>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @account.desc %>
</p>

<p>
  <b>Account:</b>
  <%= @account.account %>
</p>

<p>
  <b>User:</b>
  <%= User.find(@account.user_id).username %>
</p>

<div class="button-group">
	<%= link_to 'Edit', edit_account_path(@account), :class => "button primary" %>
	<%= link_to 'Back', dashboard_path, :class => "button danger" %>
</div>
<br/>
<br/>
<br/>
<br/>
<h2>Listing payments</h2>


<table>
  <tr>
    <th>Amount</th>
    <th>Desc</th>
    <th>Status</th>
    <th>Document</th>
    <th>Account</th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.amount %></td>
    <td><%= payment.desc %></td>
    <td><%= payment.status %></td>
    <td><%= payment.document %></td>
	<td>
		<div class="button-group">
			<%= link_to 'Show', account_payment_path(@account,payment),:class => "button primary" %>
			<%= link_to 'Edit', edit_account_payment_path(@account,payment), :class => "button" %>
			<%= link_to 'Destroy', account_payment_path(@account,payment), confirm: 'Are you sure?', method: :delete, :class => "button danger" %>
		</div>
	</td>
  </tr>
<% end %>
</table>

<br/>
<br/>
<br/>
<br/>

<!--%= link_to 'New payment', new_account_payment_path(@account), :class => "button icon add" %-->

<%= form_for([@account,@account.payments.build]) do |f| %>
  
  <div class="clearfix">
    <%= f.label :amount %>
	<div class="input">
		<%= f.text_field :amount %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :desc %>
	<div class="input">
		<%= f.text_field :desc %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :status %>
	<div class="input">
		<%= f.text_field :status %>
	</div>
  </div>
  <div class="clearfix">
    <%= f.label :document %>
	<div class="input">
		<%= f.text_field :document %>
	</div>
  </div>

  <div class="input">
    <%= f.submit :class => "button primary" %>
  </div>
<% end %>